### ISSUE TITLE
palette 수정

### ISSUE THREAD

**Issue by jindonyy** [Co-Studo/cos-ui#12]
## 수정 내용
colors로 import하여 사용하는 색상들 palette에 추가

### 추가할 colors
- white
- grey200, grey700
- greyOpacity100, greyOpacity500

### 수정할 components
<img width="355" alt="스크린샷 2022-12-01 오전 4 01 25" src="https://user-images.githubusercontent.com/17706346/204885566-fa322ea9-9455-48c9-8c29-e8531b52f1dc.png">

**Comment by healtheloper** [comment]
#19
