### ISSUE TITLE
라이브러리 번들러 적용

### ISSUE THREAD

**Issue by healtheloper** [Co-Studo/cos-ui#63]
## 예상 동작

현재 Storybook 실행 시 alias 관련 에러 발생중입니다.
원인은 babel.config.js 에서 사용중인 module-resolver 가 현재 경로를 기준으로 경로를 resolve 하기 때문에 storybook 을 실행시키면 root 의 babel 을 참고하여 사용하고, root 를 기준으로 resolve 하기 때문에 경로차이가 발생합니다. 
이 문제를 해결하기 위해서 [`../../../src` -> `../src` 등으로 바꿔 사용했었습니다.](https://github.com/Co-Studo/cos-ui/pull/51)

하지만 당시에도 이런 방법이 일시적일 수 밖에 없음을 알고있었고, 폴더의 depth 가 깊어질수록 `../../../../src`등의 경로를 추가해야하기 때문에 본질적인 문제를 해결하는게 필요하다고 생각했습니다.

<img width="837" alt="스크린샷 2023-05-04 오후 3 44 25" src="https://user-images.githubusercontent.com/58503584/236400296-c0234b15-4a39-4a3e-b9bf-22fd5de91eda.png">

-  primitives 에 story 를 추가하니, context 라는 폴더가 있는 Slider 에서 오류가 발생한 모습

.babelrc ([babelrc 와 babel config 의 차이](https://babeljs.io/docs/config-files/#configuration-file-types)) 로 바꾸어 사용하는 방버도 있겠으나, 현재 모노레포로 사용하고 있으니 이를 해결하기 위해 다른 걸 바꾸는 느낌이어서, 차라리 alias 를 해결하기 위한 방법을 바꾸는게 낫겠다고 생각이 들어 라이브러리 번들러 적용을 하는게 낫겠다 판단했습니다.

도입 시 장점

1. 용량
2. 현재 에러를 해결할 수 있음

+) 
해당 작업을 위한 issues
- [x] #65
- [x] #68

**Comment by healtheloper** [comment]
@hemudi alias 관련 작업을 하다보니 컴포넌트들을 제공하는 primitives, react 패키지에서 굳이 절대경로를 사용해야할까 라는 의문이 드는데 어떻게 생각하시나요?
alias 를 쓰는 이유는 깊어지는 directory 경로에 따라 상대경로가 무수히 길어져서 불편하기 때문에 사용한다고 생각하는데, 컴포넌트 라이브러리의 경우 directory 의 depth 가 깊어질 상황이 없지 않을까 싶어 의문이 들었습니다

**Comment by hemudi** [comment]
@healtheloper
확실히 co-studo 에서 그대로 옮겨오면서 자연스럽게 절대경로를 쓰고 있었어서 현 패키지에 절대 경로가 맞는지에 대한 고민을 안 해봤었네요
저도 절대 경로는 디렉터리 깊이가 깊어지는 문제를 해결하기 위해 도입해왔어서 파크의 의문에 공감이 갑니다.
상대 경로로 하기로 했을 때 우려되는 점은 모든 파일들의 경로를 수정해야해서 좀 번거로울 것 같다는 점인데 현재의 문제를 별도의 기능 추가 없이 컨벤션을 수정하는 것으로 해결할 수 있다고 생각하면 오히려 이득이 크다고 느껴지네요!
저는 찬성하겠습니다!
